### ISSUE TITLE
guided_denovo_circle_structure_parallel - wrong path

### ISSUE THREAD

**Issue by CDieterich** [dieterich-lab/FUCHS#11]
**Programm call:**
python /beegfs/homes/cdieterich/software/DCC/DCC_env/bin/guided_denovo_circle_structure_parallel -c 10 -A /prj/circRNA_age_brain/agingMice/FUCHS_Step3/workflow/FUCHS/mm10.ensembl.exons.bed -T /scratch/cdieterich/ -I 1746_F_FUCHS/ -N 1746_F

**after some time it throws:**

Traceback (most recent call last):
  File "/beegfs/homes/cdieterich/software/DCC/DCC_env/bin/guided_denovo_circle_structure_parallel", line 4, in <module>
    __import__('pkg_resources').run_script('FUCHS==0.1.0', 'guided_denovo_circle_structure_parallel')
  File "/beegfs/homes/cdieterich/software/DCC/DCC_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 744, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/beegfs/homes/cdieterich/software/DCC/DCC_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/beegfs/homes/cdieterich/software/DCC/DCC_env/lib/python2.7/site-packages/FUCHS-0.1.0-py2.7.egg/EGG-INFO/scripts/guided_denovo_circle_structure_parallel", line 443, in <module>
    (filename, introns) = result.get()
  File "/biosw/python2/2.7.11/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
ValueError: /beegfs/homes/cdieterich/software/DCC/DCC_env/lib/python2.7/site-packages/pybedtools-0.7.9-py2.7-linux-x86_64.egg/pybedtools/test/data/1746_F_FUCHS//1746_F//10_10698048_10782794_15reads.sorted.bam does not exist

It seems that the path to the bam file is not correctly built
BTW, the file exists in the working directory under 1746_F_FUCHS/1746_F

**Comment by FranziMe** [comment]
Hi,

I am very sorry, but I cannot reproduce the error. I did encounter this problem a while ago but fixed it with the commit aec8dadd3d0eb15e46690974af94fef95c4fb53e. Have you tried forcing the installation after pulling the lasts commits?
python setup.py install --user --force

**Comment by CDieterich** [comment]
This fixes the problem indeed. Thank you !
