### ISSUE TITLE
some issues with FUCHS

### ISSUE THREAD

**Issue by CYZbasebio** [dieterich-lab/FUCHS#12]
Hi，

I found some issues here：

1. when set -N HCOA1_new， there is a new directory named “HCOA1_new” created in output fold (many bam files and bai files in this fold)， BUT FUCHS will get a error like this:
![default](https://cloud.githubusercontent.com/assets/27392315/24987203/344bf2c6-2031-11e7-972b-48ccb90c8e69.png)
I guess FUCHS want say "/DataProcess/Project/qindanProject/Arabidopsis_thaliana/circular_RNA/test20170412_FUCHS/HCOA1_new"。

2. FUCHS option “-s” means SKIPPED_STEPS， but in manual，it means "character used to separate name and exon number". 

3. what the Annotation.bed file should be? what's the difference between "refseq" and "ensembl" specify by option -p, how -e control FUCHS get what it want. I do suggest authors write a real detailed and reproducible workflow for FUCHS, thanks a lot.

4. here is my command used：
FUCHS -r 2 -q 2 -p ensembl -e 2 -T ~/tmp -D CircRNACount -J HCOA1.Chimeric.out.junction -F HCOA1.mate1.Chimeric.out.junction -R HCOA1.mate2.Chimeric.out.junction.fixed -B merged_HCOA1.sorted.bam -A Arabidopsis_thaliana.refseq2.bed -N HCOA1_new

5. here is annotation.bed used:
1	3630	3913	AT1G01010.1_exon_1_0_1_3631_f	0	+
1	3995	4276	AT1G01010.1_exon_2_0_1_3996_f	0	+
1	4485	4605	AT1G01010.1_exon_3_0_1_4486_f	0	+

**Comment by CYZbasebio** [comment]
when I give FUCHS a created fold "/DataProcess/Project/qindanProject/Arabidopsis_thaliana/circular_RNA/test20170412_FUCHS/demoOUT/HCOA1" (set -N HCOA1 -O demoOUT), FUCHS seems found what it want and run forward. A new error found:
Traceback (most recent call last):
  File "/usr/local/bin/FUCHS", line 11, in <module>
    load_entry_point('FUCHS==0.1.0', 'console_scripts', 'FUCHS')()
  File "/usr/local/lib/python2.7/dist-packages/FUCHS-0.1.0-py2.7.egg/FUCHS/FUCHS.py", line 258, in main
    sv.run()
  File "/usr/local/lib/python2.7/dist-packages/FUCHS-0.1.0-py2.7.egg/FUCHS/get_coverage_profile.py", line 305, in run
    self.platform)
  File "/usr/local/lib/python2.7/dist-packages/FUCHS-0.1.0-py2.7.egg/FUCHS/get_coverage_profile.py", line 140, in circle_coverage_profile
    coverage = virtual_bed.coverage(bam, d=True, split=True)
  File "/usr/local/lib/python2.7/dist-packages/pybedtools/bedtool.py", line 775, in decorated
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pybedtools/bedtool.py", line 337, in wrapped
    decode_output=decode_output,
  File "/usr/local/lib/python2.7/dist-packages/pybedtools/helpers.py", line 356, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError: 
Command was:

	bedtools coverage -split -d -b /DataProcess/Project/qindanProject/Arabidopsis_thaliana/circular_RNA/test20170412_FUCHS/demoOUT/HCOA1/1_24301628_24302463_4reads.sorted.bam -a /home/yuanzhi/tmp/pybedtools.i6GLrN.tmp

Error message was:
Unexpected file format.  Please use tab-delimited BED, GFF, or VCF. Perhaps you have non-integer starts or ends at line 1?

**Comment by FranziMe** [comment]
Hi CYZbasebio,

Thanks for your report. Which bedtools version is in your PATH? 
I will try to take care of the first issue as soon as possible.

Thanks!
